# Uptime-Kuma-Service-Push - Configuration file
# YAML isn't parsed through a YAML processor so be 
# careful editing the config options.
# Example:
#
# module:
#   variable: string
#
# Always make sure the top-level 'module:' is empty
# and that the required 'variable:'s has a value.
# For more info, see 'uptime-kuma-service-push config --help'

# Options for Uptime-Kuma-Service-Push general options.
config:
  configured: false
  installed: false

# Options for the 'generate' command.
generate:
  file_name: name.sh
  folder_location: ./push-scripts
